import { TFTSet } from './types'

export const sampleTFTSet: TFTSet = {
  name: 'Set 13 - Into the Arcane',
  traits: [
    { id: 'academy', name: 'Academy', color: 'oklch(0.75 0.15 280)' },
    { id: 'ambusher', name: 'Ambusher', color: 'oklch(0.60 0.20 340)' },
    { id: 'artillerist', name: 'Artillerist', color: 'oklch(0.70 0.20 30)' },
    { id: 'bruiser', name: 'Bruiser', color: 'oklch(0.65 0.15 15)' },
    { id: 'cabal', name: 'Cabal', color: 'oklch(0.50 0.25 310)' },
    { id: 'chem-baron', name: 'Chem-Baron', color: 'oklch(0.65 0.20 120)' },
    { id: 'conqueror', name: 'Conqueror', color: 'oklch(0.70 0.22 10)' },
    { id: 'dominator', name: 'Dominator', color: 'oklch(0.55 0.22 350)' },
    { id: 'emissary', name: 'Emissary', color: 'oklch(0.80 0.12 200)' },
    { id: 'enforcer', name: 'Enforcer', color: 'oklch(0.65 0.18 250)' },
    { id: 'experiment', name: 'Experiment', color: 'oklch(0.75 0.18 160)' },
    { id: 'family', name: 'Family', color: 'oklch(0.75 0.12 140)' },
    { id: 'firelight', name: 'Firelight', color: 'oklch(0.70 0.25 45)' },
    { id: 'formswapper', name: 'Form Swapper', color: 'oklch(0.80 0.15 320)' },
    { id: 'highroller', name: 'High Roller', color: 'oklch(0.85 0.18 80)' },
    { id: 'junkerking', name: 'Junker King', color: 'oklch(0.60 0.15 60)' },
    { id: 'pit-fighter', name: 'Pit Fighter', color: 'oklch(0.68 0.20 20)' },
    { id: 'quickstriker', name: 'Quickstriker', color: 'oklch(0.75 0.20 200)' },
    { id: 'rebel', name: 'Rebel', color: 'oklch(0.70 0.25 25)' },
    { id: 'scrap', name: 'Scrap', color: 'oklch(0.65 0.12 70)' },
    { id: 'sentinel', name: 'Sentinel', color: 'oklch(0.72 0.16 260)' },
    { id: 'sniper', name: 'Sniper', color: 'oklch(0.65 0.15 100)' },
    { id: 'sorcerer', name: 'Sorcerer', color: 'oklch(0.70 0.22 270)' },
    { id: 'visionary', name: 'Visionary', color: 'oklch(0.78 0.20 290)' },
    { id: 'watcher', name: 'Watcher', color: 'oklch(0.60 0.18 220)' },
  ],
  champions: [
    { id: 'darius', name: 'Darius', cost: 1, traits: ['conqueror', 'pit-fighter'] },
    { id: 'lest', name: 'Lest', cost: 1, traits: ['cabal', 'ambusher'] },
    { id: 'maddie', name: 'Maddie', cost: 1, traits: ['enforcer', 'artillerist'] },
    { id: 'powder', name: 'Powder', cost: 1, traits: ['family', 'ambusher'] },
    { id: 'singed', name: 'Singed', cost: 1, traits: ['chem-baron', 'experiment'] },
    { id: 'steb', name: 'Steb', cost: 1, traits: ['enforcer', 'watcher'] },
    { id: 'trundle', name: 'Trundle', cost: 1, traits: ['scrap', 'bruiser'] },
    { id: 'vander', name: 'Vander', cost: 1, traits: ['family', 'bruiser'] },
    { id: 'zyra', name: 'Zyra', cost: 1, traits: ['experiment', 'sorcerer'] },
    
    { id: 'blitzcrank', name: 'Blitzcrank', cost: 2, traits: ['scrap', 'sentinel'] },
    { id: 'camille', name: 'Camille', cost: 2, traits: ['enforcer', 'ambusher'] },
    { id: 'draven', name: 'Draven', cost: 2, traits: ['pit-fighter', 'highroller'] },
    { id: 'irelia', name: 'Irelia', cost: 2, traits: ['sentinel', 'quickstriker'] },
    { id: 'leona', name: 'Leona', cost: 2, traits: ['academy', 'sentinel'] },
    { id: 'nocturne', name: 'Nocturne', cost: 2, traits: ['experiment', 'quickstriker'] },
    { id: 'rell', name: 'Rell', cost: 2, traits: ['conqueror', 'watcher'] },
    { id: 'renni', name: 'Renni', cost: 2, traits: ['chem-baron', 'ambusher'] },
    { id: 'smeech', name: 'Smeech', cost: 2, traits: ['scrap', 'ambusher'] },
    { id: 'tristana', name: 'Tristana', cost: 2, traits: ['family', 'artillerist'] },
    { id: 'urgot', name: 'Urgot', cost: 2, traits: ['pit-fighter', 'experiment'] },
    { id: 'violet', name: 'Violet', cost: 2, traits: ['enforcer', 'pit-fighter', 'quickstriker'] },
    { id: 'vladmir', name: 'Vladimir', cost: 2, traits: ['cabal', 'sorcerer'] },
    
    { id: 'akali', name: 'Akali', cost: 3, traits: ['firelight', 'ambusher', 'quickstriker'] },
    { id: 'cassiopeia', name: 'Cassiopeia', cost: 3, traits: ['cabal', 'dominator'] },
    { id: 'corki', name: 'Corki', cost: 3, traits: ['scrap', 'artillerist'] },
    { id: 'ezreal', name: 'Ezreal', cost: 3, traits: ['academy', 'artillerist'] },
    { id: 'gangplank', name: 'Gangplank', cost: 3, traits: ['pit-fighter', 'highroller'] },
    { id: 'heimerdinger', name: 'Heimerdinger', cost: 3, traits: ['academy', 'visionary'] },
    { id: 'kogmaw', name: "Kog'Maw", cost: 3, traits: ['experiment', 'sniper'] },
    { id: 'loris', name: 'Loris', cost: 3, traits: ['enforcer', 'sentinel', 'watcher'] },
    { id: 'nami', name: 'Nami', cost: 3, traits: ['emissary', 'sorcerer'] },
    { id: 'nunu', name: 'Nunu', cost: 3, traits: ['experiment', 'bruiser'] },
    { id: 'renata', name: 'Renata', cost: 3, traits: ['chem-baron', 'visionary'] },
    { id: 'scar', name: 'Scar', cost: 3, traits: ['firelight', 'watcher'] },
    { id: 'sett', name: 'Sett', cost: 3, traits: ['firelight', 'pit-fighter', 'bruiser'] },
    { id: 'swain', name: 'Swain', cost: 3, traits: ['conqueror', 'visionary', 'sorcerer'] },
    { id: 'twitch', name: 'Twitch', cost: 3, traits: ['experiment', 'sniper'] },
    { id: 'vex', name: 'Vex', cost: 3, traits: ['emissary', 'sorcerer'] },
    { id: 'ziggs', name: 'Ziggs', cost: 3, traits: ['scrap', 'dominator'] },
    
    { id: 'ambessa', name: 'Ambessa', cost: 4, traits: ['emissary', 'conqueror', 'quickstriker'] },
    { id: 'dr-mundo', name: 'Dr. Mundo', cost: 4, traits: ['experiment', 'dominator', 'bruiser'] },
    { id: 'ekko', name: 'Ekko', cost: 4, traits: ['firelight', 'scrap', 'formswapper'] },
    { id: 'elise', name: 'Elise', cost: 4, traits: ['emissary', 'academy', 'formswapper'] },
    { id: 'garen', name: 'Garen', cost: 4, traits: ['emissary', 'sentinel', 'watcher'] },
    { id: 'illaoi', name: 'Illaoi', cost: 4, traits: ['emissary', 'dominator', 'watcher'] },
    { id: 'jinx', name: 'Jinx', cost: 4, traits: ['rebel', 'ambusher', 'formswapper'] },
    { id: 'norra-yuumi', name: 'Norra & Yuumi', cost: 4, traits: ['emissary', 'visionary', 'sorcerer'] },
    { id: 'silco', name: 'Silco', cost: 4, traits: ['chem-baron', 'cabal', 'dominator'] },
    { id: 'twisted-fate', name: 'Twisted Fate', cost: 4, traits: ['highroller', 'sorcerer'] },
    { id: 'vi', name: 'Vi', cost: 4, traits: ['enforcer', 'pit-fighter', 'watcher'] },
    { id: 'zeri', name: 'Zeri', cost: 4, traits: ['firelight', 'sniper'] },
    { id: 'zoe', name: 'Zoe', cost: 4, traits: ['visionary', 'sorcerer'] },
    
    { id: 'caitlyn', name: 'Caitlyn', cost: 5, traits: ['enforcer', 'sniper'] },
    { id: 'jayce', name: 'Jayce', cost: 5, traits: ['academy', 'formswapper', 'artillerist'] },
    { id: 'leblanc', name: 'LeBlanc', cost: 5, traits: ['cabal', 'dominator', 'sorcerer'] },
    { id: 'mordekaiser', name: 'Mordekaiser', cost: 5, traits: ['conqueror', 'dominator', 'bruiser'] },
    { id: 'rumble', name: 'Rumble', cost: 5, traits: ['scrap', 'visionary', 'bruiser'] },
    { id: 'sevika', name: 'Sevika', cost: 5, traits: ['chem-baron', 'pit-fighter', 'bruiser'] },
    { id: 'warwick', name: 'Warwick', cost: 5, traits: ['experiment', 'bruiser'] },
    
    { id: 'mel', name: 'Mel', cost: 6, traits: ['emissary', 'visionary'] },
  ],
}
