import { TFTSet } from './types'

export const set13: TFTSet = {
  id: 'set13',
  name: 'Set 13 - Into the Arcane',
  traits: [
    { id: 'academy', name: 'Academy', color: 'oklch(0.60 0.32 265)' },
    { id: 'ambusher', name: 'Ambusher', color: 'oklch(0.48 0.35 345)' },
    { id: 'artillerist', name: 'Artillerist', color: 'oklch(0.62 0.33 35)' },
    { id: 'bruiser', name: 'Bruiser', color: 'oklch(0.55 0.32 18)' },
    { id: 'cabal', name: 'Cabal', color: 'oklch(0.42 0.35 305)' },
    { id: 'chem-baron', name: 'Chem-Baron', color: 'oklch(0.55 0.33 135)' },
    { id: 'conqueror', name: 'Conqueror', color: 'oklch(0.58 0.34 12)' },
    { id: 'dominator', name: 'Dominator', color: 'oklch(0.46 0.33 352)' },
    { id: 'emissary', name: 'Emissary', color: 'oklch(0.65 0.28 195)' },
    { id: 'enforcer', name: 'Enforcer', color: 'oklch(0.52 0.32 245)' },
    { id: 'experiment', name: 'Experiment', color: 'oklch(0.62 0.32 165)' },
    { id: 'family', name: 'Family', color: 'oklch(0.68 0.28 145)' },
    { id: 'firelight', name: 'Firelight', color: 'oklch(0.60 0.35 48)' },
    { id: 'formswapper', name: 'Form Swapper', color: 'oklch(0.72 0.30 315)' },
    { id: 'highroller', name: 'High Roller', color: 'oklch(0.75 0.32 85)' },
    { id: 'junkerking', name: 'Junker King', color: 'oklch(0.50 0.30 62)' },
    { id: 'pit-fighter', name: 'Pit Fighter', color: 'oklch(0.56 0.33 22)' },
    { id: 'quickstriker', name: 'Quickstriker', color: 'oklch(0.58 0.33 205)' },
    { id: 'rebel', name: 'Rebel', color: 'oklch(0.56 0.35 28)' },
    { id: 'scrap', name: 'Scrap', color: 'oklch(0.54 0.28 72)' },
    { id: 'sentinel', name: 'Sentinel', color: 'oklch(0.56 0.30 255)' },
    { id: 'sniper', name: 'Sniper', color: 'oklch(0.55 0.30 108)' },
    { id: 'sorcerer', name: 'Sorcerer', color: 'oklch(0.55 0.33 275)' },
    { id: 'visionary', name: 'Visionary', color: 'oklch(0.63 0.32 285)' },
    { id: 'watcher', name: 'Watcher', color: 'oklch(0.48 0.32 225)' },
  ],
  champions: [
    { id: 'darius', name: 'Darius', cost: 1, traits: ['conqueror', 'pit-fighter'] },
    { id: 'lest', name: 'Lest', cost: 1, traits: ['cabal', 'ambusher'] },
    { id: 'maddie', name: 'Maddie', cost: 1, traits: ['enforcer', 'artillerist'] },
    { id: 'powder', name: 'Powder', cost: 1, traits: ['family', 'ambusher'] },
    { id: 'singed', name: 'Singed', cost: 1, traits: ['chem-baron', 'experiment'] },
    { id: 'steb', name: 'Steb', cost: 1, traits: ['enforcer', 'watcher'] },
    { id: 'trundle', name: 'Trundle', cost: 1, traits: ['scrap', 'bruiser'] },
    { id: 'vander', name: 'Vander', cost: 1, traits: ['family', 'bruiser'] },
    { id: 'zyra', name: 'Zyra', cost: 1, traits: ['experiment', 'sorcerer'] },
    
    { id: 'blitzcrank', name: 'Blitzcrank', cost: 2, traits: ['scrap', 'sentinel'] },
    { id: 'camille', name: 'Camille', cost: 2, traits: ['enforcer', 'ambusher'] },
    { id: 'draven', name: 'Draven', cost: 2, traits: ['pit-fighter', 'highroller'] },
    { id: 'irelia', name: 'Irelia', cost: 2, traits: ['sentinel', 'quickstriker'] },
    { id: 'leona', name: 'Leona', cost: 2, traits: ['academy', 'sentinel'] },
    { id: 'nocturne', name: 'Nocturne', cost: 2, traits: ['experiment', 'quickstriker'] },
    { id: 'rell', name: 'Rell', cost: 2, traits: ['conqueror', 'watcher'] },
    { id: 'renni', name: 'Renni', cost: 2, traits: ['chem-baron', 'ambusher'] },
    { id: 'smeech', name: 'Smeech', cost: 2, traits: ['scrap', 'ambusher'] },
    { id: 'tristana', name: 'Tristana', cost: 2, traits: ['family', 'artillerist'] },
    { id: 'urgot', name: 'Urgot', cost: 2, traits: ['pit-fighter', 'experiment'] },
    { id: 'violet', name: 'Violet', cost: 2, traits: ['enforcer', 'pit-fighter', 'quickstriker'] },
    { id: 'vladmir', name: 'Vladimir', cost: 2, traits: ['cabal', 'sorcerer'] },
    
    { id: 'akali', name: 'Akali', cost: 3, traits: ['firelight', 'ambusher', 'quickstriker'] },
    { id: 'cassiopeia', name: 'Cassiopeia', cost: 3, traits: ['cabal', 'dominator'] },
    { id: 'corki', name: 'Corki', cost: 3, traits: ['scrap', 'artillerist'] },
    { id: 'ezreal', name: 'Ezreal', cost: 3, traits: ['academy', 'artillerist'] },
    { id: 'gangplank', name: 'Gangplank', cost: 3, traits: ['pit-fighter', 'highroller'] },
    { id: 'heimerdinger', name: 'Heimerdinger', cost: 3, traits: ['academy', 'visionary'] },
    { id: 'kogmaw', name: "Kog'Maw", cost: 3, traits: ['experiment', 'sniper'] },
    { id: 'loris', name: 'Loris', cost: 3, traits: ['enforcer', 'sentinel', 'watcher'] },
    { id: 'nami', name: 'Nami', cost: 3, traits: ['emissary', 'sorcerer'] },
    { id: 'nunu', name: 'Nunu', cost: 3, traits: ['experiment', 'bruiser'] },
    { id: 'renata', name: 'Renata', cost: 3, traits: ['chem-baron', 'visionary'] },
    { id: 'scar', name: 'Scar', cost: 3, traits: ['firelight', 'watcher'] },
    { id: 'sett', name: 'Sett', cost: 3, traits: ['firelight', 'pit-fighter', 'bruiser'] },
    { id: 'swain', name: 'Swain', cost: 3, traits: ['conqueror', 'visionary', 'sorcerer'] },
    { id: 'twitch', name: 'Twitch', cost: 3, traits: ['experiment', 'sniper'] },
    { id: 'vex', name: 'Vex', cost: 3, traits: ['emissary', 'sorcerer'] },
    { id: 'ziggs', name: 'Ziggs', cost: 3, traits: ['scrap', 'dominator'] },
    
    { id: 'ambessa', name: 'Ambessa', cost: 4, traits: ['emissary', 'conqueror', 'quickstriker'] },
    { id: 'dr-mundo', name: 'Dr. Mundo', cost: 4, traits: ['experiment', 'dominator', 'bruiser'] },
    { id: 'ekko', name: 'Ekko', cost: 4, traits: ['firelight', 'scrap', 'formswapper'] },
    { id: 'elise', name: 'Elise', cost: 4, traits: ['emissary', 'academy', 'formswapper'] },
    { id: 'garen', name: 'Garen', cost: 4, traits: ['emissary', 'sentinel', 'watcher'] },
    { id: 'illaoi', name: 'Illaoi', cost: 4, traits: ['emissary', 'dominator', 'watcher'] },
    { id: 'jinx', name: 'Jinx', cost: 4, traits: ['rebel', 'ambusher', 'formswapper'] },
    { id: 'norra-yuumi', name: 'Norra & Yuumi', cost: 4, traits: ['emissary', 'visionary', 'sorcerer'] },
    { id: 'silco', name: 'Silco', cost: 4, traits: ['chem-baron', 'cabal', 'dominator'] },
    { id: 'twisted-fate', name: 'Twisted Fate', cost: 4, traits: ['highroller', 'sorcerer'] },
    { id: 'vi', name: 'Vi', cost: 4, traits: ['enforcer', 'pit-fighter', 'watcher'] },
    { id: 'zeri', name: 'Zeri', cost: 4, traits: ['firelight', 'sniper'] },
    { id: 'zoe', name: 'Zoe', cost: 4, traits: ['visionary', 'sorcerer'] },
    
    { id: 'caitlyn', name: 'Caitlyn', cost: 5, traits: ['enforcer', 'sniper'] },
    { id: 'jayce', name: 'Jayce', cost: 5, traits: ['academy', 'formswapper', 'artillerist'] },
    { id: 'leblanc', name: 'LeBlanc', cost: 5, traits: ['cabal', 'dominator', 'sorcerer'] },
    { id: 'mordekaiser', name: 'Mordekaiser', cost: 5, traits: ['conqueror', 'dominator', 'bruiser'] },
    { id: 'rumble', name: 'Rumble', cost: 5, traits: ['scrap', 'visionary', 'bruiser'] },
    { id: 'sevika', name: 'Sevika', cost: 5, traits: ['chem-baron', 'pit-fighter', 'bruiser'] },
    { id: 'warwick', name: 'Warwick', cost: 5, traits: ['experiment', 'bruiser'] },
    
    { id: 'mel', name: 'Mel', cost: 6, traits: ['emissary', 'visionary'] },
  ],
}

export const set14: TFTSet = {
  id: 'set14',
  name: "Set 14 - Magic n' Mayhem",
  traits: [
    { id: 'arcana', name: 'Arcana', color: 'oklch(0.60 0.33 280)' },
    { id: 'automata', name: 'Automata', color: 'oklch(0.54 0.30 198)' },
    { id: 'bastion', name: 'Bastion', color: 'oklch(0.56 0.28 238)' },
    { id: 'bat-queen', name: 'Bat Queen', color: 'oklch(0.42 0.33 328)' },
    { id: 'blackrose', name: 'Black Rose', color: 'oklch(0.36 0.35 348)' },
    { id: 'blaster', name: 'Blaster', color: 'oklch(0.60 0.34 32)' },
    { id: 'chronos', name: 'Chronos', color: 'oklch(0.62 0.32 182)' },
    { id: 'dragon', name: 'Dragon', color: 'oklch(0.56 0.35 16)' },
    { id: 'eldritch', name: 'Eldritch', color: 'oklch(0.46 0.32 292)' },
    { id: 'faerie', name: 'Faerie', color: 'oklch(0.68 0.30 145)' },
    { id: 'frost', name: 'Frost', color: 'oklch(0.62 0.32 218)' },
    { id: 'honeymancy', name: 'Honeymancy', color: 'oklch(0.72 0.33 82)' },
    { id: 'hunter', name: 'Hunter', color: 'oklch(0.50 0.32 112)' },
    { id: 'incantor', name: 'Incantor', color: 'oklch(0.56 0.32 308)' },
    { id: 'mage', name: 'Mage', color: 'oklch(0.55 0.34 268)' },
    { id: 'multistriker', name: 'Multistriker', color: 'oklch(0.58 0.32 42)' },
    { id: 'portal', name: 'Portal', color: 'oklch(0.54 0.33 298)' },
    { id: 'preserver', name: 'Preserver', color: 'oklch(0.63 0.30 162)' },
    { id: 'pyro', name: 'Pyro', color: 'oklch(0.56 0.35 36)' },
    { id: 'scholar', name: 'Scholar', color: 'oklch(0.58 0.30 258)' },
    { id: 'shapeshifter', name: 'Shapeshifter', color: 'oklch(0.55 0.32 188)' },
    { id: 'sugarcraft', name: 'Sugarcraft', color: 'oklch(0.70 0.32 338)' },
    { id: 'vanguard', name: 'Vanguard', color: 'oklch(0.54 0.30 248)' },
    { id: 'warrior', name: 'Warrior', color: 'oklch(0.55 0.33 12)' },
    { id: 'witchcraft', name: 'Witchcraft', color: 'oklch(0.50 0.33 318)' },
  ],
  champions: [
    { id: 'ashe', name: 'Ashe', cost: 1, traits: ['eldritch', 'multistriker'] },
    { id: 'blitzcrank', name: 'Blitzcrank', cost: 1, traits: ['honeymancy', 'vanguard'] },
    { id: 'elise', name: 'Elise', cost: 1, traits: ['eldritch', 'shapeshifter'] },
    { id: 'jax', name: 'Jax', cost: 1, traits: ['chronos', 'multistriker'] },
    { id: 'jayce', name: 'Jayce', cost: 1, traits: ['portal', 'shapeshifter'] },
    { id: 'lillia', name: 'Lillia', cost: 1, traits: ['faerie', 'bastion'] },
    { id: 'nomsy', name: 'Nomsy', cost: 1, traits: ['dragon', 'hunter'] },
    { id: 'poppy', name: 'Poppy', cost: 1, traits: ['witchcraft', 'bastion'] },
    { id: 'seraphine', name: 'Seraphine', cost: 1, traits: ['faerie', 'mage'] },
    { id: 'soraka', name: 'Soraka', cost: 1, traits: ['sugarcraft', 'mage'] },
    { id: 'twitch', name: 'Twitch', cost: 1, traits: ['frost', 'hunter'] },
    { id: 'warwick', name: 'Warwick', cost: 1, traits: ['frost', 'vanguard'] },
    { id: 'ziggs', name: 'Ziggs', cost: 1, traits: ['honeymancy', 'incantor'] },
    
    { id: 'ahri', name: 'Ahri', cost: 2, traits: ['arcana', 'scholar'] },
    { id: 'akali', name: 'Akali', cost: 2, traits: ['pyro', 'multistriker', 'warrior'] },
    { id: 'cassiopeia', name: 'Cassiopeia', cost: 2, traits: ['incantor', 'witchcraft'] },
    { id: 'galio', name: 'Galio', cost: 2, traits: ['portal', 'vanguard', 'mage'] },
    { id: 'kassadin', name: 'Kassadin', cost: 2, traits: ['portal', 'multistriker'] },
    { id: 'kog-maw', name: "Kog'Maw", cost: 2, traits: ['honeymancy', 'hunter'] },
    { id: 'nilah', name: 'Nilah', cost: 2, traits: ['eldritch', 'warrior'] },
    { id: 'nunu', name: 'Nunu', cost: 2, traits: ['honeymancy', 'bastion'] },
    { id: 'rumble', name: 'Rumble', cost: 2, traits: ['sugarcraft', 'blaster', 'vanguard'] },
    { id: 'shaco', name: 'Shaco', cost: 2, traits: ['witchcraft', 'multistriker'] },
    { id: 'syndra', name: 'Syndra', cost: 2, traits: ['eldritch', 'incantor'] },
    { id: 'tristana', name: 'Tristana', cost: 2, traits: ['faerie', 'blaster'] },
    { id: 'vex', name: 'Vex', cost: 2, traits: ['chrono', 'mage'] },
    
    { id: 'bard', name: 'Bard', cost: 3, traits: ['sugarcraft', 'scholar', 'preserver'] },
    { id: 'ezreal', name: 'Ezreal', cost: 3, traits: ['portal', 'blaster'] },
    { id: 'hecarim', name: 'Hecarim', cost: 3, traits: ['arcana', 'bastion', 'multistriker'] },
    { id: 'hwei', name: 'Hwei', cost: 3, traits: ['frost', 'blaster'] },
    { id: 'jinx', name: 'Jinx', cost: 3, traits: ['sugarcraft', 'hunter'] },
    { id: 'katarina', name: 'Katarina', cost: 3, traits: ['faerie', 'warrior'] },
    { id: 'mordekaiser', name: 'Mordekaiser', cost: 3, traits: ['eldritch', 'vanguard'] },
    { id: 'neeko', name: 'Neeko', cost: 3, traits: ['witchcraft', 'shapeshifter'] },
    { id: 'shen', name: 'Shen', cost: 3, traits: ['pyro', 'bastion'] },
    { id: 'swain', name: 'Swain', cost: 3, traits: ['frost', 'shapeshifter'] },
    { id: 'veigar', name: 'Veigar', cost: 3, traits: ['honeymancy', 'mage'] },
    { id: 'wukong', name: 'Wukong', cost: 3, traits: ['druid'] },
    
    { id: 'fiora', name: 'Fiora', cost: 4, traits: ['witchcraft', 'warrior'] },
    { id: 'gwen', name: 'Gwen', cost: 4, traits: ['sugarcraft', 'warrior'] },
    { id: 'karma', name: 'Karma', cost: 4, traits: ['chrono', 'incantor'] },
    { id: 'kalista', name: 'Kalista', cost: 4, traits: ['faerie', 'multistriker'] },
    { id: 'nami', name: 'Nami', cost: 4, traits: ['eldritch', 'mage'] },
    { id: 'nasus', name: 'Nasus', cost: 4, traits: ['pyro', 'shapeshifter'] },
    { id: 'norra', name: 'Norra & Yuumi', cost: 4, traits: ['portal', 'mage'] },
    { id: 'olaf', name: 'Olaf', cost: 4, traits: ['frost', 'hunter'] },
    { id: 'rakan', name: 'Rakan', cost: 4, traits: ['faerie', 'preserver'] },
    { id: 'ryze', name: 'Ryze', cost: 4, traits: ['portal', 'scholar'] },
    { id: 'tahm-kench', name: 'Tahm Kench', cost: 4, traits: ['arcana', 'vanguard'] },
    { id: 'taric', name: 'Taric', cost: 4, traits: ['portal', 'bastion'] },
    
    { id: 'briar', name: 'Briar', cost: 5, traits: ['eldritch', 'shapeshifter', 'warrior'] },
    { id: 'camille', name: 'Camille', cost: 5, traits: ['chrono', 'multistriker'] },
    { id: 'diana', name: 'Diana', cost: 5, traits: ['frost', 'bastion'] },
    { id: 'milio', name: 'Milio', cost: 5, traits: ['faerie', 'scholar'] },
    { id: 'morgana', name: 'Morgana', cost: 5, traits: ['bat-queen', 'preserver', 'witchcraft'] },
    { id: 'smolder', name: 'Smolder', cost: 5, traits: ['dragon', 'blaster'] },
    { id: 'xerath', name: 'Xerath', cost: 5, traits: ['arcana', 'ascendant'] },
    { id: 'zoe', name: 'Zoe', cost: 5, traits: ['portal', 'witchcraft', 'scholar'] },
  ],
}

export const set17: TFTSet = {
  id: 'set17',
  name: 'Set 17 - Inkborn Fables 2',
  traits: [
    { id: 'arcanist', name: 'Arcanist', color: 'oklch(0.56 0.34 278)' },
    { id: 'artillerist', name: 'Artillerist', color: 'oklch(0.60 0.33 32)' },
    { id: 'automata', name: 'Automata', color: 'oklch(0.54 0.30 198)' },
    { id: 'bruiser', name: 'Bruiser', color: 'oklch(0.54 0.33 18)' },
    { id: 'challenger', name: 'Challenger', color: 'oklch(0.58 0.32 342)' },
    { id: 'invoker', name: 'Invoker', color: 'oklch(0.60 0.33 268)' },
    { id: 'preserver', name: 'Preserver', color: 'oklch(0.63 0.32 162)' },
    { id: 'sentinel', name: 'Sentinel', color: 'oklch(0.56 0.32 238)' },
    { id: 'sniper', name: 'Sniper', color: 'oklch(0.54 0.30 102)' },
    { id: 'vanguard', name: 'Vanguard', color: 'oklch(0.54 0.30 248)' },
    { id: 'warden', name: 'Warden', color: 'oklch(0.56 0.28 218)' },
    { id: 'exalted', name: 'Exalted', color: 'oklch(0.72 0.33 62)' },
    { id: 'heavenly', name: 'Heavenly', color: 'oklch(0.68 0.32 82)' },
    { id: 'ink', name: 'Ink', color: 'oklch(0.42 0.33 288)' },
    { id: 'mythic', name: 'Mythic', color: 'oklch(0.63 0.33 308)' },
    { id: 'porcelain', name: 'Porcelain', color: 'oklch(0.74 0.24 178)' },
    { id: 'sage', name: 'Sage', color: 'oklch(0.56 0.32 142)' },
    { id: 'storyweaver', name: 'Storyweaver', color: 'oklch(0.61 0.32 318)' },
    { id: 'umbral', name: 'Umbral', color: 'oklch(0.36 0.33 298)' },
  ],
  champions: [
    { id: 'amumu', name: 'Amumu', cost: 1, traits: ['porcelain', 'warden'] },
    { id: 'annie', name: 'Annie', cost: 1, traits: ['exalted', 'invoker'] },
    { id: 'ashe', name: 'Ashe', cost: 1, traits: ['porcelain', 'sniper'] },
    { id: 'malphite', name: 'Malphite', cost: 1, traits: ['heavenly', 'sentinel'] },
    { id: 'rakan', name: 'Rakan', cost: 1, traits: ['heavenly', 'preserver'] },
    { id: 'shen', name: 'Shen', cost: 1, traits: ['sage', 'sentinel'] },
    { id: 'sivir', name: 'Sivir', cost: 1, traits: ['umbral', 'challenger'] },
    { id: 'teemo', name: 'Teemo', cost: 1, traits: ['exalted', 'sniper'] },
    { id: 'thresh', name: 'Thresh', cost: 1, traits: ['umbral', 'warden'] },
    { id: 'xayah', name: 'Xayah', cost: 1, traits: ['heavenly', 'challenger'] },
    
    { id: 'ahri', name: 'Ahri', cost: 2, traits: ['exalted', 'arcanist'] },
    { id: 'darius', name: 'Darius', cost: 2, traits: ['umbral', 'bruiser'] },
    { id: 'gnar', name: 'Gnar', cost: 2, traits: ['mythic', 'bruiser'] },
    { id: 'janna', name: 'Janna', cost: 2, traits: ['sage', 'invoker'] },
    { id: 'kindred', name: 'Kindred', cost: 2, traits: ['mythic', 'sniper'] },
    { id: 'kog-maw', name: "Kog'Maw", cost: 2, traits: ['ink', 'artillerist'] },
    { id: 'neeko', name: 'Neeko', cost: 2, traits: ['mythic', 'arcanist'] },
    { id: 'ornn', name: 'Ornn', cost: 2, traits: ['exalted', 'vanguard'] },
    { id: 'qiyana', name: 'Qiyana', cost: 2, traits: ['umbral', 'challenger'] },
    { id: 'syndra', name: 'Syndra', cost: 2, traits: ['storyweaver', 'invoker'] },
    { id: 'yone', name: 'Yone', cost: 2, traits: ['exalted', 'challenger'] },
    
    { id: 'alune', name: 'Alune', cost: 3, traits: ['umbral', 'invoker'] },
    { id: 'azir', name: 'Azir', cost: 3, traits: ['porcelain', 'automata'] },
    { id: 'ezreal', name: 'Ezreal', cost: 3, traits: ['porcelain', 'artillerist'] },
    { id: 'irelia', name: 'Irelia', cost: 3, traits: ['storyweaver', 'challenger'] },
    { id: 'jax', name: 'Jax', cost: 3, traits: ['ink', 'vanguard'] },
    { id: 'kayn', name: 'Kayn', cost: 3, traits: ['umbral', 'challenger'] },
    { id: 'lee-sin', name: 'Lee Sin', cost: 3, traits: ['mythic', 'sage', 'bruiser'] },
    { id: 'lillia', name: 'Lillia', cost: 3, traits: ['mythic', 'invoker'] },
    { id: 'nautilus', name: 'Nautilus', cost: 3, traits: ['ink', 'warden'] },
    { id: 'sylas', name: 'Sylas', cost: 3, traits: ['storyweaver', 'bruiser'] },
    { id: 'tristana', name: 'Tristana', cost: 3, traits: ['heavenly', 'artillerist'] },
    { id: 'wukong', name: 'Wukong', cost: 3, traits: ['sage', 'challenger'] },
    { id: 'zyra', name: 'Zyra', cost: 3, traits: ['storyweaver', 'arcanist'] },
    
    { id: 'galio', name: 'Galio', cost: 4, traits: ['porcelain', 'sentinel'] },
    { id: 'hwei', name: 'Hwei', cost: 4, traits: ['ink', 'arcanist'] },
    { id: 'lux', name: 'Lux', cost: 4, traits: ['porcelain', 'arcanist'] },
    { id: 'morgana', name: 'Morgana', cost: 4, traits: ['sage', 'preserver'] },
    { id: 'riven', name: 'Riven', cost: 4, traits: ['storyweaver', 'bruiser'] },
    { id: 'senna', name: 'Senna', cost: 4, traits: ['ink', 'sniper'] },
    { id: 'sett', name: 'Sett', cost: 4, traits: ['exalted', 'warden'] },
    { id: 'soraka', name: 'Soraka', cost: 4, traits: ['heavenly', 'preserver'] },
    { id: 'tahm-kench', name: 'Tahm Kench', cost: 4, traits: ['mythic', 'bruiser'] },
    { id: 'volibear', name: 'Volibear', cost: 4, traits: ['heavenly', 'vanguard'] },
    
    { id: 'bard', name: 'Bard', cost: 5, traits: ['mythic', 'preserver'] },
    { id: 'kai-sa', name: "Kai'Sa", cost: 5, traits: ['ink', 'invoker'] },
    { id: 'lissandra', name: 'Lissandra', cost: 5, traits: ['porcelain', 'arcanist'] },
    { id: 'oriana', name: 'Orianna', cost: 5, traits: ['exalted', 'automata'] },
    { id: 'sion', name: 'Sion', cost: 5, traits: ['storyweaver', 'sentinel'] },
    { id: 'udyr', name: 'Udyr', cost: 5, traits: ['heavenly', 'sage', 'warden'] },
    { id: 'yorick', name: 'Yorick', cost: 5, traits: ['umbral', 'warden'] },
  ],
}

export const tftSets = [set13, set14, set17]

export const sampleTFTSet = set17
